Qubic Metrics
qubic/explorer-frontend pull request #192
Opened 2024-11-21 04:03 UTC by tomaspozo

The Qubic Metrics project adds new visualizations that display historic data from different sources in the Qubic ecosystem. These new visualizations lived in the Analytics page, and include the following features:

- Market cap and price values on a daily basis 
- Weekly scores statistics chart
- Solutions tracking chart with a 5 minute granularity.
- Solutions per hour tracking with a 20 minute granularity.
-Several statistics around the Qubic open source repositories like starts, issues, and others.

New libraries:
- For charting we added tremor and its dependencies. All tremor components live under `src/components/tremor`.

Required env variables:
- VITE_METRICS_API_URL: the url of the QubicMetrics backend
- VITE_METRICS_API_TOKEN: a public key to authenticate the API calls

2024-11-21 17:21 UTC, alexmf91 requested changes
Overall looks good, you did a good job! But there are some things that are required to change to follow project patterns. Also I have seen that ui is not fully responsive. Please take a look to all comments carefully and fix them. Thanks!!!

![Screenshot 2024-11-21 at 18 20 45](https://github.com/user-attachments/assets/7ba8b4e8-e935-48e3-8f37-300b30c891bf)

2024-11-21 17:21 UTC, alexmf91 commented on CHANGELOG.md
> +## What's Changed
This shouldn't be commited, I think that your first commit of the pr is not made from latest dev branch, you would need to add the pr from latest dev status and not include changelog like this one, cause this are triggered from root repo on staging and main branches

2024-11-21 17:21 UTC, alexmf91 commented on package.json
> +    "qubic-ts-library": "^0.1.2",
Remove this library, since has been deprecated, we already have the latest version of the library, it's:
`"@qubic-lib/qubic-ts-library"`

2024-11-21 17:21 UTC, alexmf91 commented on public/locales/es/analytics-page.json
> +{
you're missing translations for all languages, please add them.

2024-11-21 17:21 UTC, alexmf91 commented on package.json
> +    "nuqs": "^2.1.1",
Why did you install this nuqs library? We are already using react router dom and if you need to interact with query params you can use: https://reactrouter.com/en/main/hooks/use-search-params

2024-11-21 17:21 UTC, alexmf91 commented on src/components/tremor/Tooltip.tsx
> +interface TooltipProps
We already have a tooltip component, do not install external libraries like radix ui please. You can enhance current Tooltip component to your needs

2024-11-21 17:21 UTC, alexmf91 commented on src/components/tremor/chartsUtils.ts
> +export function hasOnlyOneValueForKey(array: any[], keyToCheck: string): boolean {
Don't use any types please

2024-11-21 17:21 UTC, alexmf91 commented on src/components/tremor/chartsUtils.ts
> +/* eslint-disable-file @typescript-eslint/no-explicit-any */
Remove this disabling linter rule please and fix types accordingly

2024-11-21 17:21 UTC, alexmf91 commented on src/App.tsx
> +            <NuqsAdapter>
Remove this nuqs adapter please

2024-11-21 17:21 UTC, alexmf91 commented on src/components/ui/DateRangeSelector.tsx
> +function formatDate(date: Date) {
We already have a formatDate util func in utils folder, you can check if you can rehuse that one and enhance it if needed. Let's not create dupe funcs.

2024-11-21 17:21 UTC, alexmf91 commented on src/components/ui/layouts/Header.tsx
> +    <header className="relative mx-auto flex items-center justify-between gap-6 border-b border-primary-60 p-20">
We are going to update header component with this new design: https://www.figma.com/design/uTkCAs5q8c1UiV9PPPRGcS/Qubic-apps?node-id=2995-754&node-type=frame&t=ashwOHGYuVuQbrJk-0

Can you update it your added tab following that layout please?

2024-11-21 17:21 UTC, alexmf91 commented on src/components/ui/layouts/Header.tsx
> +              true ? 'bg-primary-60 text-white' : 'text-gray-600 hover:text-gray-800',
This makes no sense: true ? ..

2024-11-21 17:21 UTC, alexmf91 commented on src/hooks/useOnWindowResize.tsx
> +// Tremor useOnWindowResize [v0.0.0]
Remove this comment

2024-11-21 17:21 UTC, alexmf91 commented on src/hooks/useOnWindowResize.tsx
> +import * as React from 'react'
Don't use react namespace like this, import just what you need please

2024-11-21 17:21 UTC, alexmf91 commented on src/hooks/useOnWindowResize.tsx
> +  React.useEffect(() => {
Refactor this to be just useEffect

2024-11-21 17:21 UTC, alexmf91 commented on src/pages/analytics/AnalyticsPage.tsx
> +import HistoryCharts from './components/HistoryCharts'
If all of this components are imported from same folder, you can add a barrel there and import hem all with a single import line, like I do in other places

2024-11-21 17:21 UTC, alexmf91 commented on src/pages/analytics/components/CardItem.tsx
> +export default function CardItem({ children, className }: Props) {
There is already a CardItem component in network/components. Remove this one and rehuse the other one. If needs to be rehused can be moved to the top level components folder, but I may probably would put analytics folder under network folder cause is related to that IMO

2024-11-21 17:21 UTC, alexmf91 commented on src/pages/analytics/components/HistoryCharts.tsx
> +import { ComboChart } from '@app/components/tremor/ComboChart'
Try to follow barrel export pattern:
import { ComboChart } from '@app/components/tremor

2024-11-21 17:21 UTC, alexmf91 commented on src/pages/analytics/components/HistoryCharts.tsx
> +                  ({calculateVariance(data, 'marketCap')})
memoize this value with useMemo

2024-11-21 17:21 UTC, alexmf91 commented on src/pages/analytics/components/HomeLink.tsx
> +export default function HomeLink() {
There is already a home link component in network components, remove this one please

2024-11-21 17:21 UTC, alexmf91 commented on src/pages/analytics/components/OverviewCardItem.tsx
> +export default function OverviewCardItem({
This component is almost the same of the original OverviewCardItem, use the other one, don't duplicate components

2024-11-21 17:21 UTC, alexmf91 commented on src/pages/analytics/components/ReposHistoryChart.tsx
> +      categories={['starsCount', 'commits', 'openIssues', 'closedIssues', 'watchersCount']}
Put this array data on top of the component, is going to be recreated on every render like it is. like const CATEGORIES = [...]

2024-11-21 17:21 UTC, alexmf91 commented on src/pages/analytics/components/ReposHistoryChart.tsx
> +      colors={['gray', 'gray', 'gray', 'gray', 'gray']}
Same here

2024-11-21 17:21 UTC, alexmf91 commented on src/pages/analytics/components/ScoresHistoryCharts.tsx
> +                ({calculateVariance(data, 'averageScore')})
wrap this in a useMemo

2024-11-21 17:21 UTC, alexmf91 commented on src/pages/analytics/components/SolutionsChart.tsx
> +import { useGetQubicLIScoresHistoryQuery } from '@app/store/apis/metrics-v1.api'
group imports by: external libraries, @app.. , and relative imports ( like scope imports)

2024-11-21 17:21 UTC, alexmf91 commented on src/pages/analytics/components/SolutionsPerHourChart.tsx
> +            categories={['solutionsPerHour', 'allTimeSolutionsPerHour']}
Put this oustide the component, on top of the file

2024-11-21 17:21 UTC, alexmf91 commented on src/pages/analytics/components/SubCardItem.tsx
> +import { clsxTwMerge } from '@app/utils'
This component is exatly the same that we have on network, don't duplicate components please

2024-11-21 17:21 UTC, alexmf91 commented on src/router/router.tsx
> +import AnalyticsPage from '@app/pages/analytics/AnalyticsPage'
Relocate this page under network folder and Lazy load this page following the pattern we use

2024-11-21 17:21 UTC, alexmf91 commented on src/store/apis/metrics-v1.api.ts
> +export const metricsV1Api = createApi({
if there is no live v2 version, just name it as metricsApi, rename it in all places please

2024-11-21 17:21 UTC, alexmf91 commented on src/components/tremor/ComboChart.tsx
> +import { useOnWindowResize } from '@app/hooks/useOnWindowResize'
Same here, split this in to smaller files. Don't use any external libraries like remix icons, you can use what we already have and if it's not enough you can add it on assets and folow the pattern we do

2024-11-21 17:21 UTC, alexmf91 commented on package.json
> +    "@radix-ui/react-tooltip": "^1.1.3",
Remove this library. we  already have tooltip component

2024-11-21 17:21 UTC, alexmf91 commented on package.json
> +    "@remixicon/react": "^4.2.0",
Remove this library, use existing icons or add them manually from heroicons

2024-11-21 17:21 UTC, alexmf91 commented on src/components/tremor/AreaChart.tsx
> +import { RiArrowLeftSLine, RiArrowRightSLine } from '@remixicon/react'
This large files are not acceptable, split this in to small components, also don't use react namespace and external libraries for icons. Components should be max 150 - 300 lines of code if it's possible

2024-11-21 17:50 UTC, tomaspozo commented on CHANGELOG.md
> +## What's Changed
yeah, looks like an error on commits, I removed that first commit

2024-11-25 23:53 UTC, tomaspozo commented
Qubic team has asked that Qubic Metrics be a independent project and code. Closing this PR since we won't be merging this code. Thank you!

2024-11-25 23:53 UTC, closed without merging